#!/bin/bash
#SBATCH --account=hpc1f17
#SBATCH --partition=largemem ##debug
#SBATCH --job-name="P2"
#SBATCH --output=P2-%j.out
#SBATCH --error=P2-%j.err
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=32
##SBATCH --mem=4800
#SBATCH --time=02:00:00
#SBATCH --constraint=IB
#SBATCH --mail-user=ninastei@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue

module load intel/17.0
module load intel-mpi/2017.0.1
module list

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

srun ../bin/P2P1a.mpi>P2P1a.txt
srun ../bin/P2P3a.mpi>P2P3a.txt
echo "AND LO!"
