#!/bin/bash
#SBATCH --partition=debug
#SBATCH --job-name="mpipi"
#SBATCH --output=mpipi-%j.out
#SBATCH --error=mpipi-%j.err
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=12
##SBATCH --mem=4800
#SBATCH --time=00:05:00
#SBATCH --constraint=IB&CPU-E5645
#SBATCH --mail-user=ninastei@buffalo.edu
#SBATCH --mail-type=ALL
#SBATCH --requeue

module load intel/17.0
module load intel-mpi/2017.0.1
module list

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

srun ~/CCR/execs/pi.mpi

echo "AND LO!"
